version: "3.1"
services:
  # Symfony
  symfony:
    image: nginx:alpine
    ports:
      - 80:80
    working_dir: /application
    volumes:
        - ./backend:/application
        - ./backend/.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: backend/.docker/php-fpm
    working_dir: /application
    volumes:
      - ./backend:/application
      - ./backend/.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=dear_recruity

  mongo:
    image: mongo
    ports:
      - 27017:27017
